### ISSUE TITLE
Make achievements notification when you get them

### ISSUE THREAD

**Issue by farisfaikar** [farisfaikar/Number-Game-v0.1#50]
I thought it would be cool for the players to get notified once they achieved an achievement. I'm not sure how the system should work, but I want it to be simple.

**Comment by redromnon** [comment]
Hi there! I'm interested in adding this feature. Please assign this.

Moreover, can you please elaborate the "achivement" part?

**Comment by R0merol** [comment]
For example, when the player completes the first achievement, which is "I did it!", a small window will pop out from below, stating that the player has completed said achievement. However, it must be able to handle multiple achievements popping out at the same time, which is a possible problem with this system. The message should be, (for the first achievement); "Achievement Unlocked: I did it!". The message should be contained in a box and pops out from below the screen and disappears after a few seconds. If multiple achievements are unlocked at the same time, they should wait for each other to pop out and disappear. It'll be awesome if you could make it happen!

**Comment by redromnon** [comment]
Cool.
Are achievements 5 & 6 not implemented yet? I cannot see those in `achievement.py`

**Comment by R0merol** [comment]
It should be in-game pop-ups, not desktop ones from windows. So you basically have to do things from scratch I'm afraid

**Comment by redromnon** [comment]
Hello,
I won't be able to add this feature anytime soon. I request you to please unassign me.

**Comment by R0merol** [comment]
Okay, thanks for taking interest in this issue

**Comment by UjjwalAggarwal-1** [comment]
please assign this to me, i'd like to try

**Comment by R0merol** [comment]
Good luck!

**Comment by UjjwalAggarwal-1** [comment]
Incase of multiple achivements, how about showing all the achivements in one popup

**Comment by UjjwalAggarwal-1** [comment]
may i go on with tkinter?

**Comment by R0merol** [comment]
> may i go on with tkinter?

Not sure if it's compatible with pygame though. The popup should occur inside the game, and not on a separate window. But I'll give you the green light to try it out.

**Comment by UjjwalAggarwal-1** [comment]
![image](https://user-images.githubusercontent.com/96613056/197707259-d6faccb2-8743-4137-8221-b2e3ad5684fc.png)

have a look, it is a seperate window though

**Comment by UjjwalAggarwal-1** [comment]
i could give buttons like continue, ...

**Comment by UjjwalAggarwal-1** [comment]
pr #55

**Comment by R0merol** [comment]
> i could give buttons like continue, ...

Yes, can you add that, please? That'll be awesome

**Comment by UjjwalAggarwal-1** [comment]
this was done, so closing it
